version: '3.3'

services:
  db:
    image: postgres:14.10
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: f_back
    build: ./backend
    volumes:
      - backend_static_volume:/app/static
      - backend_media:/app/media
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: f_front
    build: ./frontend
    volumes:
      - frontend_build:/app/build

  nginx:
    container_name: f-gateway
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - backend_static_volume:/var/www/static
      - backend_media:/var/www/media
    depends_on:
      - backend
      - frontend

volumes:
  backend_static_volume:
  backend_media:
  pg_data:
  frontend_build: