name: Foodgram CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  flake8:
    name: Check Flake8
    runs-on: ubuntu-latest

    steps:
    - name: Get repository code
      uses: actions/checkout@v3

    - name: Configure Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup project requirements
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-pyproject
        pip install -r backend/requirements.txt

    - name: Run flake8
      run: |
        python -m flake8 backend/

  backend_docker:
    name: Build and push backend
    runs-on: ubuntu-latest
    needs: flake8
    if: github.event_name == 'push'
    
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      
      - name: Configure Docker environment
        uses: docker/setup-buildx-action@v2
      
      - name: Authenticate with Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest

  frontend_docker:
    name: Build and push frontend
    runs-on: ubuntu-latest
    needs: flake8
    if: github.event_name == 'push'
    
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      
      - name: Configure Docker environment
        uses: docker/setup-buildx-action@v2
      
      - name: Authenticate with Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest
